### ISSUE TITLE
SANS Securing Web Application Technologies [SWAT] Checklist

### ISSUE THREAD

**Issue by NoahJaehnert** [iamthefrogy/Application-Security#1]
Just wanted to provide the SANS Securing Web Application Technologies [SWAT] Checklist as a suggestion. I've found it incredibly useful in the past. 

https://software-security.sans.org/resources/swat

**Comment by iamthefrogy** [comment]
Sure I will add testcases from it in this mine repository if there are any missing. Appreciate your suggestion.
